---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bash-cli
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/tags: cli
    tekton.dev/displayName: "bash cli"
spec:
  description: >-
    This task runs commands against Bash.
  params:
  - name: SCRIPT
    description: The CLI commands to run
    type: string
    default: "curl $@"
  - name: ARGS
    description: The CLI arguments to run
    type: array
    default:
    - "--help"
  steps:
    - name: command
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: "$(params.SCRIPT)"
      args:
        - "$(params.ARGS)"