---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helm-rewine-pipeline
  namespace: package-deploy-staging
spec:
  tasks:
    - name: helm-upgrade-from-repo
      params:
        - name: helm_repo
          value: 'https://mcouliba.github.io/helm-charts'
        - name: chart_name
          value: mcouliba/cloud-native-java
        - name: release_version
          value: v1.0.0
        - name: release_name
          value: rewine-backend
        - name: overwrite_values
          value: >-
            image.repository=image-registry.openshift-image-registry.svc:5000/package-deploy-dev/rewine-backend,image.tag=latest
        - name: helm_version
          value: latest
        - name: release_namespace
          value: package-deploy-staging
      taskRef:
        kind: ClusterTask
        name: helm-upgrade-from-repo
    - name: deploy
      params:
        - name: SCRIPT
          value: oc $@
        - name: ARGS
          value:
            - rollout
            - status
            - deploy/rewine-backend-cloud-native-java
      runAfter:
        - helm-upgrade-from-repo
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: simu-functional-tests
      params:
        - name: SCRIPT
          value: echo $@
        - name: ARGS
          value:
            - '"Tests OK"'
      runAfter:
        - deploy
      taskRef:
        kind: Task
        name: bash-cli
    - name: simu-acceptance-tests
      params:
        - name: SCRIPT
          value: echo $@
        - name: ARGS
          value:
            - '"Tests OK"'
      runAfter:
        - deploy
      taskRef:
        kind: Task
        name: bash-cli
    - name: trigger-prod-pipeline
      params:
        - name: tkn-image
          value: >-
            gcr.io/tekton-releases/dogfooding/tkn@sha256:f79c0a56d561b1ae98afca545d0feaf2759f5c486ef891a79f23dc2451167dad
        - name: ARGS
          value:
            - pipeline
            - start
            - helm-rewine-pipeline
            - '-n'
            - package-deploy
      runAfter:
        - simu-functional-tests
        - simu-acceptance-tests
      taskRef:
        kind: ClusterTask
        name: tkn
