---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rewine-backend
  namespace: package-deploy-dev
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rewine-pipeline-pvc
  namespace: package-deploy-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helm-rewine-pipeline
  namespace: package-deploy-dev
spec:
  tasks:
    - name: git-clone-src
      params:
        - name: url
          value: 'https://github.com/Red-Wine-Software/backend'
        - name: revision
          value: summit2021
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines-tech-preview/pipelines-git-init-rhel8@sha256:0938b8d7fdf79a92f22f7ac5e4cec1896ca7b6a441bb47124c9cafdc8d1efa89
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: unit-tests
      params:
        - name: MAVEN_IMAGE
          value: >-
            gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
        - name: GOALS
          value:
            - test
        - name: MAVEN_MIRROR_URL
          value: 'http://nexus.opentlc-shared.svc:8081/repository/maven-all-public'
        - name: PROXY_PROTOCOL
          value: http
      runAfter:
        - git-clone-src
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
    - name: simu-code-quality
      params:
        - name: SCRIPT
          value: echo $@
        - name: ARGS
          value:
            - '"Tests OK"'
      runAfter:
        - git-clone-src
      taskRef:
        kind: Task
        name: bash-cli
    - name: simu-code-security
      params:
        - name: SCRIPT
          value: echo $@
        - name: ARGS
          value:
            - '"Tests OK"'
      runAfter:
        - git-clone-src
      taskRef:
        kind: Task
        name: bash-cli
    - name: build
      params:
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: MAVEN_CLEAR_REPO
          value: 'false'
        - name: MAVEN_MIRROR_URL
          value: 'http://nexus.opentlc-shared.svc:8081/repository/maven-all-public'
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/package-deploy-dev/rewine-backend
      runAfter:
        - unit-tests
        - simu-code-quality
        - simu-code-security
      taskRef:
        kind: ClusterTask
        name: s2i-java-11
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: helm-upgrade-from-repo
      params:
        - name: helm_repo
          value: 'https://mcouliba.github.io/helm-charts'
        - name: chart_name
          value: mcouliba/cloud-native-java
        - name: release_version
          value: v1.0.0
        - name: release_name
          value: rewine-backend
        - name: overwrite_values
          value: >-
            image.repository=image-registry.openshift-image-registry.svc:5000/package-deploy-dev/rewine-backend,image.tag=latest
        - name: helm_version
          value: latest
        - name: release_namespace
          value: package-deploy-dev
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: helm-upgrade-from-repo
    - name: deploy
      params:
        - name: SCRIPT
          value: oc $@
        - name: ARGS
          value:
            - rollout
            - status
            - deploy/rewine-backend-cloud-native-java
      runAfter:
        - helm-upgrade-from-repo
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: simu-integration-tests
      params:
        - name: SCRIPT
          value: echo $@
        - name: ARGS
          value:
            - '"Tests OK"'
      runAfter:
        - deploy
      taskRef:
        kind: Task
        name: bash-cli
    - name: trigger-staging-pipeline
      params:
        - name: tkn-image
          value: >-
            gcr.io/tekton-releases/dogfooding/tkn@sha256:f79c0a56d561b1ae98afca545d0feaf2759f5c486ef891a79f23dc2451167dad
        - name: ARGS
          value:
            - pipeline
            - start
            - helm-rewine-pipeline
            - '-n'
            - package-deploy-staging
      runAfter:
        - simu-integration-tests
      taskRef:
        kind: ClusterTask
        name: tkn
  workspaces:
    - name: shared-workspace
    - name: maven-settings
